# Generated by Django 5.2.2 on 2025-06-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
    ]
